# -*- coding: utf-8 -*-
"""Arima model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tmdSL2N8WALm4Th93-NFc9hHXeOOlJB
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install statsmodels tensorflow

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from sklearn.metrics import mean_absolute_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense

file_path = "/content/drive/MyDrive/supply_chain_demand_forecasting_dataset_2024_2026.csv"
df = pd.read_csv(file_path)
df.head()

df.columns = df.columns.str.lower()
date_col = [col for col in df.columns if 'date' in col][0]
if 'sales' in df.columns:
    target_col = 'sales'
else:
    target_col = 'demand'
print("Date:", date_col)
print("Target:", target_col)

df[date_col] = pd.to_datetime(df[date_col])
df = df.sort_values(date_col)
ts = df.groupby(date_col)[target_col].sum()

train_size = int(len(ts) * 0.8)
train = ts[:train_size]
test = ts[train_size:]

model = ARIMA(train, order=(5,1,0))
model_fit = model.fit()

predictions = model_fit.forecast(steps=len(test))

plt.figure(figsize=(10,5))
plt.plot(test.index, test.values, label="Actual")
plt.plot(test.index, predictions, label="ARIMA Prediction")
plt.legend()
plt.title("ARIMA Forecast vs Actual")
plt.show()

mae = mean_absolute_error(test, predictions)
print("ARIMA MAE:", mae)

from sklearn.metrics import mean_squared_error
import numpy as np

def smape(actual, predicted):
    return 100/len(actual) * np.sum(
        2 * np.abs(predicted - actual) / (np.abs(actual) + np.abs(predicted))
    )
rmse_arima = np.sqrt(mean_squared_error(test, predictions))
smape_arima = smape(test.values, predictions)
print("ARIMA RMSE:", rmse_arima)
print("ARIMA SMAPE:", smape_arima)