# -*- coding: utf-8 -*-
"""TFT model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z2Qlz2b_CGUzVDC1F5HWshubq_0u46CN
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install lightning pytorch-forecasting torchmetrics

!pip install lightning pytorch-forecasting torchmetrics scikit-learn

import pandas as pd
import torch
import lightning.pytorch as pl
from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import SMAPE

import pandas as pd
import torch
import numpy as np
import lightning.pytorch as pl

from pytorch_forecasting import TimeSeriesDataSet, TemporalFusionTransformer
from pytorch_forecasting.data import GroupNormalizer
from pytorch_forecasting.metrics import SMAPE

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error

file_path = "/content/drive/MyDrive/supply_chain_demand_forecasting_dataset_2024_2026.csv"
df = pd.read_csv(file_path)
df.head()

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values("date").reset_index(drop=True)

df["time_idx"] = df.index
df["series_id"] = "0"
for lag in [1, 2, 3, 7, 14, 30]:
    df[f"lag_{lag}"] = df["sales"].shift(lag)
df["rolling_mean_7"] = df["sales"].rolling(7).mean()
df["rolling_std_7"] = df["sales"].rolling(7).std()

df = df.dropna()
scaler = StandardScaler()
df["sales"] = scaler.fit_transform(df[["sales"]])

df["date"] = pd.to_datetime(df["date"])
df = df.sort_values(by="date").reset_index(drop=True)
df["time_idx"] = df.index
df["series_id"] = "0" # Assuming a single time series for simplicity
max_encoder_length = 90
max_prediction_length = 30
training_cutoff = df["time_idx"].max() - max_prediction_length

max_encoder_length = 150
max_prediction_length = 30

training_cutoff = df["time_idx"].max() - max_prediction_length

training = TimeSeriesDataSet(
    df[df.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="sales",
    group_ids=["series_id"],

    max_encoder_length=max_encoder_length,
    max_prediction_length=max_prediction_length,

    static_categoricals=["series_id"],

    time_varying_known_reals=[
        "time_idx", "day_of_week", "month",
        "is_holiday", "is_promotion", "oil_price"
    ],

    time_varying_unknown_reals=[
        "sales",
        "lag_1","lag_2","lag_3","lag_7","lag_14","lag_30",
        "rolling_mean_7","rolling_std_7"
    ],

    target_normalizer=GroupNormalizer(groups=["series_id"]),
)

validation = TimeSeriesDataSet.from_dataset(training, df, predict=True, stop_randomization=True)

train_loader = training.to_dataloader(train=True, batch_size=256)
val_loader = validation.to_dataloader(train=False, batch_size=256)

training = TimeSeriesDataSet(
    df[df.time_idx <= training_cutoff],
    time_idx="time_idx",
    target="sales",
    group_ids=["series_id"],

    max_encoder_length=max_encoder_length,
    max_prediction_length=max_prediction_length,

    static_categoricals=["series_id"],

    time_varying_known_reals=[
        "time_idx",
        "day_of_week",
        "month",
        "is_holiday",
        "is_promotion",
        "oil_price"
    ],

    time_varying_unknown_reals=["sales"],

    target_normalizer=GroupNormalizer(groups=["series_id"]),
)

validation = TimeSeriesDataSet.from_dataset(
    training, df, predict=True, stop_randomization=True
)

train_loader = training.to_dataloader(train=True, batch_size=64)
val_loader = validation.to_dataloader(train=False, batch_size=64)

tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.001,
    hidden_size=16,
    attention_head_size=4,
    dropout=0.1,
    hidden_continuous_size=8,
    loss=SMAPE(),
    output_size=1
)

trainer = pl.Trainer(
    max_epochs=15,
    accelerator="gpu",
    devices=1,
)

trainer.fit(
    model=tft,
    train_dataloaders=train_loader,
    val_dataloaders=val_loader
)

output = tft.predict(
    val_loader,
    mode="raw",
    return_x=True
)

raw_predictions, x = output[0], output[1]
tft.plot_prediction(x, raw_predictions, idx=0)

import numpy as np

def create_sequences(data, seq_length=90):
    X, y = [], []
    for i in range(len(data) - seq_length):
        X.append(data[i:i+seq_length])
        y.append(data[i+seq_length])
    return np.array(X), np.array(y)

sales = df["sales"].values
X, y = create_sequences(sales)

X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.float32)

train_size = int(0.8 * len(X))
X_train, X_val = X[:train_size], X[train_size:]
y_train, y_val = y[:train_size], y[train_size:]

import torch.nn as nn

class SalesTransformer(nn.Module):
    def __init__(self):
        super().__init__()
        self.embedding = nn.Linear(1, 32)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model=32, nhead=4, batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=2)
        self.fc = nn.Linear(32, 1)

    def forward(self, x):
        x = x.unsqueeze(-1)
        x = self.embedding(x)
        x = self.transformer(x)
        return self.fc(x[:, -1])

model = SalesTransformer().cuda()
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

for epoch in range(10):
    model.train()
    optimizer.zero_grad()

    output = model(X_train.cuda())
    loss = criterion(output.squeeze(), y_train.cuda())

    loss.backward()
    optimizer.step()

    print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

from pytorch_forecasting.metrics import QuantileLoss

tft = TemporalFusionTransformer.from_dataset(
    training,
    learning_rate=0.001,
    hidden_size=16,
    attention_head_size=4,
    dropout=0.1,
    hidden_continuous_size=8,
    loss=QuantileLoss(quantiles=[0.1, 0.5, 0.9]),
    output_size=3
)

output = tft.predict(
    val_loader,
    mode="raw",
    return_x=True
)
raw_predictions, x = output[0], output[1]

import numpy as np
pred = raw_predictions.prediction.cpu().numpy()
p10 = pred[0, :, 0]
p50 = pred[0, :, 1]
p90 = pred[0, :, 2]
actual = x["decoder_target"][0].cpu().numpy()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(actual, label="Actual", linewidth=2)
plt.plot(p50, label="P50 (Median Forecast)", linestyle="--")
plt.fill_between(
    range(len(p50)),
    p10,
    p90,
    alpha=0.3,
    label="P10–P90 (Uncertainty Range)"
)
plt.title("Demand Forecast with Uncertainty (Cone of Uncertainty)")
plt.xlabel("Time Steps (Next 30 Days)")
plt.ylabel("Sales")
plt.legend()
plt.grid()
plt.show()

from sklearn.metrics import mean_absolute_error
preds = p50
actuals = x["decoder_target"].cpu().numpy().flatten()
mae_tft = mean_absolute_error(actuals, preds)
print("TFT MAE:", mae_tft)

from sklearn.metrics import mean_squared_error
import numpy as np

def smape(actual, predicted):
    numerator = np.abs(predicted - actual)
    denominator = (np.abs(actual) + np.abs(predicted)) / 2
    ratio = np.where(denominator == 0, 0, numerator / denominator)
    return np.mean(ratio) * 100

preds = p50
actuals = x["decoder_target"].cpu().numpy().flatten()
rmse_tft = np.sqrt(mean_squared_error(actuals, preds))
smape_tft = smape(actuals, preds)
print("TFT RMSE:", rmse_tft)
print("TFT SMAPE:", smape_tft)